# IFTTT
- alias: IFTTT
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
#
# Default theme
- id: '1160451022067'
  alias: Default Theme
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: Dark Blue
    service: frontend.set_theme
