
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 2

tts:
  - platform: google_translate

sun:
wake_on_lan:
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
light: !include lights.yaml

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

hacs:
  token: !secret HACS_Token

ifttt:
  key: !secret IFTTT_Key

wemo:
  static:
    - !secret Wemo_Living_Room_IP
    - !secret Wemo_Bedroom_IP

remote:
  - platform: harmony
    name: LR Harmony Hub
    host: !secret LR_Harmony_IP
    port: !secret H_Hub_Port
  - platform: harmony
    name: BR Harmony Hub
    host: !secret BR_Harmony_IP
    port: !secret H_Hub_Port

notify:
  - platform: joaoapps_join
    api_key: !secret Join_api_key
    device_ids: !secret Join_device_ids
    device_names: PC, Juan's phone, Antonette's phone
    name: All
  - platform: joaoapps_join
    api_key: !secret Join_api_key
    device_id: !secret Join_PC_id
    device_names: PC
    name: PC
  - platform: joaoapps_join
    api_key: !secret Join_api_key
    device_id: !secret Join_Juan_phone_id
    device_names: Juan's phone
    name: Juan's phone
  - platform: joaoapps_join
    api_key: !secret Join_api_key
    device_id: !secret Join_Antonette_phone_id
    device_names: Antonette's phone
    name: Antonette's phone

joaoapps_join:
  - name: Join Devices
    device_id: group.all
    api_key: !secret Join_api_key


weather:
  - platform: darksky
    api_key: !secret DarkSky_API_Key

media_player:
  - platform: braviatv
    host: !secret Living_room_TV_IP
    name: LR Sony TV

influxdb:
  host: !secret InfluxDB_Host
  port: !secret InfluxDB_Port
  database: homeassistant
  username: !secret InfluxDB_Username
  password: !secret InfluxDB_Password
  max_retries: 2
  default_measurement: state