# Living room light
- platform: template
  lights:
    living_room_light:
      friendly_name: Living room light
      value_template: "{{ is_state('switch.living_room_light', 'on') }}"
      turn_on:
        service: switch.turn_on
        data_template:
          entity_id: switch.living_room_light
      turn_off:
        service: switch.turn_off
        data_template:
          entity_id: switch.living_room_light
#
# Bedroom light
- platform: template
  lights:
    bedroom_light:
      friendly_name: Bedroom light
      value_template: "{{ is_state('switch.bedroom_light', 'on') }}"
      turn_on:
        service: switch.turn_on
        data_template:
          entity_id: switch.bedroom_light
      turn_off:
        service: switch.turn_off
        data_template:
          entity_id: switch.bedroom_light
#
# Main desk light
- platform: template
  lights:
    main_desk_light:
      friendly_name: Main desk light
      value_template: "{{ is_state('switch.main_desk_light_relay', 'on') }}"
      turn_on:
        service: switch.turn_on
        data_template:
          entity_id: switch.main_desk_light_relay
      turn_off:
        service: switch.turn_off
        data_template:
          entity_id: switch.main_desk_light_relay
#
# 2nd desk light
- platform: template
  lights:
    2nd_desk_light:
      friendly_name: 2nd desk light
      value_template: "{{ is_state('switch.2nd_desk_light_relay', 'on') }}"
      turn_on:
        service: switch.turn_on
        data_template:
          entity_id: switch.2nd_desk_light_relay
      turn_off:
        service: switch.turn_off
        data_template:
          entity_id: switch.2nd_desk_light_relay