title: Home
resources: !include_dir_list lovelace/resources
#
cch:
  swipe: true
  swipe_wrap: false
  background: var(--app-header-background-color)
#
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/kitchen.yaml