title: Home
resources:
  - url: /local/mini-media-player-bundle.js?v=1.2.0
    type: module
views:
  - title: Main
    icon: mdi:home-outline
    cards:
#
# PERSONS
      - type: entities
        show_header_toggle: false
        entities:
          - device_tracker.juan_phone
          - type: divider
          - device_tracker.antonette_phone
#
# WEATHER
      - type: weather-forecast
        name: ' '
        entity: weather.dark_sky
#
# LIGHTS
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Lights
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.main_desk_light
                name: Main desk
                tap_action:
                  action: toggle
              - type: entity-button
                entity: light.2nd_desk_light
                name: 2nd desk
                tap_action:
                  action: toggle
              - type: entity-button
                entity: light.living_room_light
                name: Living Room
                tap_action:
                  action: toggle
              - type: entity-button
                entity: light.bedroom_light
                name: bedroom
                tap_action:
                  action: toggle
#
# Home Speakers
          - type: conditional
            conditions:
              - entity: media_player.home_speakers
                state_not: "off"
              - entity: media_player.home_speakers
                state_not: "unavailable"
            card:
              type: custom:mini-media-player
              entity: media_player.home_speakers
              artwork: cover
#
# COMPUTER
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Computer
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.computer
                name: PC
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.pc_restart
                name: Restart
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.pc_lock
                name: Lock
                tap_action:
                  action: toggle
              - type: entity-button
                entity: switch.server
                name: Server
                tap_action:
                  action: toggle
#
# LIVING ROOM TV
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Living room TV
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.lr_tv_power_toggle
                name: TV
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: script.lr_cable_power_toggle
                name: Cable
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_soundbar_power_toggle
                name: Speaker
                tap_action:
                  action: toggle
              - type: entity-button
                entity: input_boolean.lr_hdmi
                name: Inputs
                tap_action:
                  action: toggle
#
# HDMI INPUTS
          - type: conditional
            conditions:
              - entity: input_boolean.lr_hdmi
                state: "on"
            card:
              type: glance
              show_name: false
              show_state: false
              entities:
                - entity: script.lr_cable_input
                  tap_action:
                    action: toggle
                - entity: script.lr_switch_input
                  tap_action:
                    action: toggle
                - entity: script.lr_netflix_input
                  tap_action:
                    action: toggle
#_#
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.lr_cable_channel_up
                name: Up
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_cable_channel_prev
                name: Prev
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_tv_volume_up
                name: Up
                tap_action:
                  action: toggle
              - type: entity-button
                entity: input_boolean.lr_playback_buttons
                name: Playback
                tap_action:
                  action: toggle
#
# PLAYBACK KEYS
          - type: conditional
            conditions:
              - entity: input_boolean.lr_playback_buttons
                state: "on"
            card:
              type: glance
              show_name: false
              show_state: false
              columns: 5
              entities:
                - entity: script.lr_cable_rewind
                  name: REW
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_play
                  name: Play
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_forward
                  name: FWD
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_direction_left
                  name: Left
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-left-bold-circle
                - entity: script.lr_cable_direction_up
                  name: Up
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-up-bold-circle
                - entity: script.lr_cable_stop
                  name: Stop
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_pause
                  name: Pause
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_select
                  name: SEL
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_direction_right
                  name: Right
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-right-bold-circle
                - entity: script.lr_cable_direction_down
                  name: Down
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-down-bold-circle
#_#
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.lr_cable_channel_down
                name: Down
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_tv_volume_mute
                name: Mute
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_tv_volume_down
                name: down
                tap_action:
                  action: toggle
              - type: entity-button
                entity: input_boolean.lr_number_pad
                name: Numbers
                tap_action:
                  action: toggle
#
# NUMBER KEYS
          - type: conditional
            conditions:
              - entity: input_boolean.lr_number_pad
                state: "on"
            card:
              type: glance
              show_name: false
              show_state: false
              columns: 3
              entities:
                - entity: script.lr_cable_number_1
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_2
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_3
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_4
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_5
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_6
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_7
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_8
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_9
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_number_0
                  tap_action:
                    action: toggle
                - entity: script.lr_cable_select
                  tap_action:
                    action: toggle
#
# CHROMECAST & GOOGLE HOME
          - type: custom:mini-media-player
            entity: media_player.living_room_speaker
            artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.living_room_tv
                state_not: "off"
              - entity: media_player.living_room_tv
                state_not: "unavailable"
            card:
              type: custom:mini-media-player
              entity: media_player.living_room_tv
              artwork: cover
#
# LIVING ROOM AC & FAN
          - type: markdown
            content: >
              ## Living room AC and Fan
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.lr_ac_power_toggle
                name: On/Off
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_ac_fan_speed
                name: Speed
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_ac_mode
                name: Mode
                icon: mdi:menu
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_ac_temp_up
                name: Up
                tap_action:
                  action: toggle
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.lr_fan_on
                name: Fan On
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_fan_off
                name: Fan Off
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_fan_airflow
                name: Airflow
                icon: mdi:swap-horizontal
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.lr_ac_temp_down
                name: Down
                tap_action:
                  action: toggle
#
#######################################################
#######################################################
#
# BEDROOM TV
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Bedroom TV
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.br_tv_power_toggle
                name: TV
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - type: entity-button
                entity: script.br_cable_power_toggle
                name: Cable
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_cable_input
                name: Live TV
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_chromecast_input
                name: Cast
                tap_action:
                  action: toggle
#_#
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.br_cable_channel_up
                name: Up
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_cable_channel_prev
                name: Prev
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_tv_volume_up
                name: Up
                tap_action:
                  action: toggle
              - type: entity-button
                entity: input_boolean.br_playback_buttons
                name: Playback
                tap_action:
                  action: toggle
#
# PLAYBACK KEYS
          - type: conditional
            conditions:
              - entity: input_boolean.br_playback_buttons
                state: "on"
            card:
              type: glance
              show_name: false
              show_state: false
              columns: 5
              entities:
                - entity: script.br_cable_rewind
                  name: REW
                  tap_action:
                    action: toggle
                - entity: script.br_cable_play
                  name: Play
                  tap_action:
                    action: toggle
                - entity: script.br_cable_forward
                  name: FWD
                  tap_action:
                    action: toggle
                - entity: script.br_cable_direction_left
                  name: Left
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-left-bold-circle
                - entity: script.br_cable_direction_up
                  name: Up
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-up-bold-circle
                - entity: script.br_cable_stop
                  name: Stop
                  tap_action:
                    action: toggle
                - entity: script.br_cable_pause
                  name: Pause
                  tap_action:
                    action: toggle
                - entity: script.br_cable_select
                  name: SEL
                  tap_action:
                    action: toggle
                - entity: script.br_cable_direction_right
                  name: Right
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-right-bold-circle
                - entity: script.br_cable_direction_down
                  name: Down
                  tap_action:
                    action: toggle
                  icon: mdi:arrow-down-bold-circle
#_#
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.br_cable_channel_down
                name: Down
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_tv_volume_mute
                name: Mute
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_tv_volume_down
                name: down
                tap_action:
                  action: toggle
              - type: entity-button
                entity: input_boolean.br_number_pad
                name: Numbers
                tap_action:
                  action: toggle
#
# NUMBER KEYS
          - type: conditional
            conditions:
              - entity: input_boolean.br_number_pad
                state: "on"
            card:
              type: glance
              show_name: false
              show_state: false
              columns: 3
              entities:
                - entity: script.br_cable_number_1
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_2
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_3
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_4
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_5
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_6
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_7
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_8
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_9
                  tap_action:
                    action: toggle
                - entity: script.br_cable_number_0
                  tap_action:
                    action: toggle
                - entity: script.br_cable_select
                  tap_action:
                    action: toggle
#
# CHROMECAST & GOOGLE HOME
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.bedroom_tv
                state_not: "off"
              - entity: media_player.bedroom_tv
                state_not: "unavailable"
            card:
              type: custom:mini-media-player
              entity: media_player.bedroom_tv
              artwork: cover
#
# BEDROOM AC & FAN
#      - type: vertical-stack
#        cards:
          - type: markdown
            content: >
              ## Bedroom AC and Fan
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.br_ac_power_toggle
                name: On/Off
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_ac_fan_speed
                name: Speed
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_ac_temp_up
                name: Up
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_ac_temp_down
                name: Down
                tap_action:
                  action: toggle
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.br_fan_on
                name: Fan On
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_fan_off
                name: Fan Off
                tap_action:
                  action: toggle
              - type: entity-button
                entity: script.br_fan_airflow
                name: Airflow
                icon: mdi:swap-horizontal
                tap_action:
                  action: toggle
#
# CHROMECAST & GOOGLE HOME (Kitchen)
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Kitchen
          - type: custom:mini-media-player
            entity: media_player.kitchen_speaker
            artwork: cover
